Cchore: Shellcheck/shfmt all the things

diff --git a/src/adr-edit b/src/adr-edit
--- a/src/adr-edit
+++ b/src/adr-edit
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -e
-eval "$($(dirname $0)/adr-config)"
+eval "$("$(dirname "$0")"/adr-config)"
 
 ## usage: adr edit [ADR_NUMBER]
 
@@ -9,30 +9,27 @@ eval "$($(dirname $0)/adr-config)"
 ## environment variable (VISUAL is preferred; EDITOR is
 ## used if VISUAL is not set).
 
-if [ ! -z "$1" ]
-then
-   editid=$(printf "%04d" $1)
+if [[ -n "$1" ]]; then
+  editid=$(printf "%04d" "$1")
 fi
 
-if [[ -z "$VISUAL" && -z "$EDITOR" ]]
-then
-   echo "ERROR: editor not configured"
-   exit 1
+if [[ -z "$VISUAL" ]] && [[ -z "$EDITOR" ]]; then
+  echo "ERROR: editor not configured"
+  exit 1
 fi
 
-dstdir=$("$adr_bin_dir/_adr_dir")
+dstdir=$("${adr_bin_dir:?}"/_adr_dir)
 
-if [[ -d $dstdir && -z "$editid" ]]
-then
-    editid=$(ls $dstdir | grep -Eo '^[0-9]+' | sort -rn | head -1)
+if [[ -d "${dstdir}" ]] && [[ -z "${editid}" ]]; then
+  # shellcheck disable=SC2010
+  editid=$(ls "${dstdir}" | grep -Eo '^[0-9]+' | sort -rn | head -1)
 fi
 
-dstfile=$dstdir/$editid-*.md
+dstfile=("${dstdir}"/"${editid}"-*.md)
 
-if [ -e $dstfile ]
-then
-   ${VISUAL:-${EDITOR:-true}} $dstfile
+if [[ -e "${dstfile[0]}" ]]; then
+  "${VISUAL:-${EDITOR:-true}}" "${dstfile[0]}"
 else
-   echo "ERROR: ADR $editid not found"
-   exit 1
-fi 
+  echo "ERROR: ADR ${editid} not found"
+  exit 1
+fi
diff --git a/src/adr-list b/src/adr-list
--- a/src/adr-list
+++ b/src/adr-list
@@ -10,30 +10,29 @@ eval "$("$(dirname "$0")"/adr-config)"
 ##
 ## -r        list decision records in reverse order
 
-adr_dir="$("$adr_bin_dir/_adr_dir")"
+adr_dir="$("${adr_bin_dir:?}"/_adr_dir)"
 
 sort_args=()
 
-if (( $# > 0 )); then
-   while getopts ":r" arg; do
-       case "${arg}" in
-           r)
-             sort_args+=("-r")
-             ;;
+if (($# > 0)); then
+  while getopts ":r" arg; do
+    case "${arg}" in
+    r)
+      sort_args+=("-r")
+      ;;
 
-           *)
-             echo "invalid argument: $OPTARG" >&2
-             exit 1
-             ;;
-       esac
-   done
-   shift $((OPTIND-1))
+    *)
+      echo "invalid argument: $OPTARG" >&2
+      exit 1
+      ;;
+    esac
+  done
+  shift $((OPTIND - 1))
 fi
 
-if [ -d "$adr_dir" ]
-then
-   find "$adr_dir" | grep -E "^$adr_dir/[0-9]+-[^/]*\\.md" | sort "${sort_args[@]}"
+if [[ -d "${adr_dir}" ]]; then
+  find "${adr_dir}" | grep -E "^${adr_dir}/[0-9]+-[^/]*\\.md" | sort "${sort_args[@]}"
 else
-    echo "The $adr_dir directory does not exist"
-    exit 1
+  echo "The ${adr_dir} directory does not exist"
+  exit 1
 fi
diff --git a/src/adr-new b/src/adr-new
--- a/src/adr-new
+++ b/src/adr-new
@@ -57,101 +57,90 @@ eval "$("$(dirname "$0")"/adr-config)"
 
 superseded=()
 links=()
-newnum=()
+newnum=unassigned
 
-while getopts n:s:l: arg
-do
-    case "$arg" in
-        n)
-            if [ -n "$newnum" ];
-            then
-                echo "ERROR: multiple numbers given"
-                exit 1
-            fi
-            newnum="$OPTARG"
-            ;;
-        s)
-            superseded+=("$OPTARG")
-            ;;
-		l)
-			links+=("$OPTARG")
-			;;
-        --)
-            break
-            ;;
-        *)
-            echo "Not implemented: $arg" >&2
-            exit 1
-            ;;
-    esac
+while getopts n:s:l: arg; do
+  case "${arg}" in
+  n)
+    if [[ "${newnum}" != unassigned ]]; then
+      echo "ERROR: multiple numbers given"
+      exit 1
+    fi
+    newnum="${OPTARG}"
+    ;;
+  s)
+    superseded+=("$OPTARG")
+    ;;
+  l)
+    links+=("$OPTARG")
+    ;;
+  *)
+    echo "Not implemented: ${arg}" >&2
+    exit 1
+    ;;
+  esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-dstdir="$("$adr_bin_dir/_adr_dir")"
+dstdir="$("${adr_bin_dir:?}"/_adr_dir)"
 template="$ADR_TEMPLATE"
-if [ -z "$template" ]
-then
-    template="$dstdir/templates/template.md"
-    if [ ! -f "$template" ]
-    then
-        template="$adr_template_dir/template.md"
-    fi
+if [[ -z "${template}" ]]; then
+  template="${dstdir}/templates/template.md"
+  if [[ ! -f "${template}" ]]; then
+    template="${adr_template_dir:?}/template.md"
+  fi
 fi
 
-title="$@"
+title="$*"
 
-if [ -z "$title" ]
-then
-    echo ERROR: no title given
-    exit 1
+if [[ -z "${title}" ]]; then
+  echo ERROR: no title given
+  exit 1
 fi
 
-if [ -z "$newnum" ]
-then
-    if [ -d "$dstdir" ]
-    then
-        maxid=$(ls "$dstdir" | grep -Eo '^[0-9]+' | sed -e 's/^0*//' | sort -rn | head -1)
-        newnum=$(($maxid + 1))
-    else
-        newnum=1
-    fi
+if [[ -z "${newnum}" ]]; then
+  if [[ -d "${dstdir}" ]]; then
+    # shellcheck disable=SC2010
+    maxid=$(ls "${dstdir}" | grep -Eo '^[0-9]+' | sed -e 's/^0*//' | sort -rn | head -1)
+    newnum=$((maxid + 1))
+  else
+    newnum=1
+  fi
 fi
 
-if ls "$dstdir"/0*"$newnum"-* 1>/dev/null 2>&1
-then
-    echo "ERROR: ADR number $newnum already exists"
-    exit 1
+if ls "${dstdir}"/0*"${newnum}"-* 1>/dev/null 2>&1; then
+  echo "ERROR: ADR number ${newnum} already exists"
+  exit 1
 fi
 
-newid=$(printf "%04d" $newnum)
-slug=$(echo -n "$title" | tr -Ccs "[:alnum:]" - | tr "[:upper:]" "[:lower:]" | sed -e 's/[^[:alnum:]]*$//' -e 's/^[^[:alnum:]]*//')
-dstfile="$dstdir/$newid-$slug.md"
+newid=$(printf "%04d" "${newnum}")
+slug=$(echo -n "${title}" | tr -Ccs "[:alnum:]" - | tr "[:upper:]" "[:lower:]" | sed -e 's/[^[:alnum:]]*$//' -e 's/^[^[:alnum:]]*//')
+dstfile="${dstdir}/${newid}-${slug}.md"
 date="${ADR_DATE:-$(date +%Y-%m-%d)}"
 
-mkdir -p "$dstdir"
-cat "$template" | sed \
-    -e "s|NUMBER|$newnum|" \
-    -e "s|TITLE|$title|" \
-    -e "s|DATE|$date|" \
-    -e "s|STATUS|Accepted|" \
-    > "$dstfile"
+mkdir -p "${dstdir}"
+sed \
+  -e "s|NUMBER|${newnum}|" \
+  -e "s|TITLE|${title}|" \
+  -e "s|DATE|${date}|" \
+  -e "s|STATUS|Accepted|" \
+  <"${template}" \
+  >"${dstfile}"
 
-for target in "${superseded[@]}"
-do
-	"$adr_bin_dir/_adr_add_link" "$target" "Superseded by" "$dstfile"
-	"$adr_bin_dir/_adr_remove_status" "Accepted" "$target"
-	"$adr_bin_dir/_adr_add_link" "$dstfile" "Supersedes" "$target"
+for target in "${superseded[@]}"; do
+  "${adr_bin_dir:?}"/_adr_add_link "${target}" "Superseded by" "${dstfile}"
+  "${adr_bin_dir:?}"/_adr_remove_status "Accepted" "${target}"
+  "${adr_bin_dir:?}"/_adr_add_link "${dstfile}" "Supersedes" "${target}"
 done
 
-for l in "${links[@]}"
-do
-	target="$(echo "$l" | cut -d : -f 1)"
-	forward_link="$(echo "$l" | cut -d : -f 2)"
-	reverse_link="$(echo "$l" | cut -d : -f 3)"
+for l in "${links[@]}"; do
+  target="$(echo "$l" | cut -d : -f 1)"
+  forward_link="$(echo "$l" | cut -d : -f 2)"
+  reverse_link="$(echo "$l" | cut -d : -f 3)"
 
-	"$adr_bin_dir/_adr_add_link" "$dstfile" "$forward_link" "$target"
-	"$adr_bin_dir/_adr_add_link" "$target" "$reverse_link" "$dstfile"
+  "${adr_bin_dir:?}"/_adr_add_link "${dstfile}" "${forward_link}" "${target}"
+  "${adr_bin_dir:?}"/_adr_add_link "${target}" "${reverse_link}" "${dstfile}"
 done
 
-"${VISUAL:-${EDITOR:-true}}" "$dstfile"
-echo "$dstfile"
+"${VISUAL:-${EDITOR:-true}}" "${dstfile}"
+echo "${dstfile}"
